### ISSUE TITLE
Environment variable for allowed hosts

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/superclusterd#1]
To prevent unauthorised access to this service, can we put an environment variable in?

**Comment by chrisdevereux** [comment]
Yeah, nice idea. If you take a look at index.js, there's a method for doing this by verifying a signature of the url, but checking the requested host against an environmental variable is much simpler!

**Comment by janbaykara** [comment]
Seems to have been solved in 84c457a8853f466286f55d3bef52faacc9f307ff
